language: java

jdk:
  - oraclejdk7

env:
  - MODULE_DIR=gtin.java
  - MODULE_DIR=gtin.js

install:
  - ./gradlew -q -b $MODULE_DIR/install.gradle install

script:
  - ./gradlew -q -b $MODULE_DIR/build.gradle clean build

after_success:
  - ./gradlew -q -b $MODULE_DIR/build.gradle coverage
