language: java

os:
  - osx

# https://github.com/travis-ci/travis-ci/issues/2317
# jdk:
#   - oraclejdk7

env:
  - MODULE_DIR=gtin.java
  - MODULE_DIR=gtin.js
  - MODULE_DIR=gtin.objc
  - MODULE_DIR=gtin.rb

install:
  - ./gradlew -q -b $MODULE_DIR/build.gradle init

script:
  - ./gradlew -q -b $MODULE_DIR/build.gradle clean build

after_success:
  - ./gradlew -q -b $MODULE_DIR/build.gradle coverage
